FROM ubuntu:18.04

RUN apt-get update && apt-get install -y --no-install-recommends \
         build-essential \
         cmake \
         git \
         curl \
         ca-certificates \
         libjpeg-dev \
         libpng-dev

RUN apt-get -y update && apt-get install -y g++ gcc gfortran build-essential git libopenblas-dev
RUN  rm -rf /var/lib/apt/lists/*

RUN curl -o ~/miniconda.sh -O  https://repo.continuum.io/miniconda/Miniconda3-4.2.12-Linux-x86_64.sh  && \
     chmod +x ~/miniconda.sh && \
     ~/miniconda.sh -b -p /opt/conda

RUN rm ~/miniconda.sh

RUN useradd -ms /bin/bash vjai

WORKDIR /tmp/
ADD ./environment-cpu.yml /tmp/environment.yml
RUN /opt/conda/bin/conda env create -f environment.yml

ENV PATH /opt/conda/envs/vjai_paper_coding/bin:/home/vjai/.local/bin:$PATH
